import type { InterviewAnswerEvaluation, InterviewQuestion } from '../../types/interview'
import { Card } from '../common/Card'
export function ReplayQuestionCard({ question, evaluation, number }: { question: InterviewQuestion; evaluation: InterviewAnswerEvaluation | null; number: number }) {
 return <Card className="p-5 sm:p-7"><div className="flex flex-wrap gap-2"><Badge>{`Question ${number}`}</Badge>{question.adaptive && <Badge>ADAPTIVE FOLLOW-UP</Badge>}<Badge>{question.category}</Badge>{question.skill && <Badge>{question.skill}</Badge>}<Badge>{question.difficulty}</Badge></div><h2 className="mt-5 text-xl font-bold leading-8">{question.questionText}</h2>
 <div className="mt-6 grid gap-5 lg:grid-cols-2"><section aria-labelledby="your-answer"><h3 id="your-answer" className="text-sm font-bold uppercase tracking-wide text-slate-500">Your Answer</h3><p className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6 dark:bg-slate-800/60">{question.answerText || 'No answer was submitted.'}</p></section><section aria-labelledby="improved-answer"><h3 id="improved-answer" className="text-sm font-bold uppercase tracking-wide text-slate-500">Example Improved Answer</h3><p className="mt-2 whitespace-pre-wrap rounded-xl bg-indigo-50 p-4 text-sm leading-6 dark:bg-indigo-950/30">{evaluation?.improvedAnswer || 'No evaluated example is available.'}</p></section></div>
 {evaluation?.status === 'COMPLETED' ? <div className="mt-6 space-y-5"><div><h3 className="font-bold">AI Evaluation Score</h3><p className="mt-1 text-2xl font-bold text-indigo-600">{evaluation.overallScore} / 100</p></div><List title="Strengths" items={evaluation.strengths}/><List title="Areas to Improve" items={evaluation.weaknesses}/><List title="Concepts to Review" items={evaluation.missingKeyPoints}/>{evaluation.summary && <div><h3 className="font-bold">Evaluation Summary</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{evaluation.summary}</p></div>}</div> : <p className="mt-6 text-sm text-slate-500">This answer has not been evaluated. Replay does not generate feedback automatically.</p>}</Card>
}
function List({title,items}:{title:string;items:string[]}){return <div><h3 className="font-bold">{title}</h3>{items.length?<ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600 dark:text-slate-300">{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul>:<p className="mt-1 text-sm text-slate-500">None recorded.</p>}</div>}
function Badge({children}:{children:string}){return <span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300">{children}</span>}
