import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Alert } from '../../components/common/Alert'
import { Card } from '../../components/common/Card'
import { LoadingSpinner } from '../../components/common/LoadingSpinner'
import { interviewService } from '../../services/interviewService'
import type { RubricAverages, TargetedPracticeSummary } from '../../types/interview'
import { getApiErrorMessage } from '../../utils/getApiErrorMessage'
export function TargetedPracticeSummaryPage(){const id=Number(useParams().id);const [data,setData]=useState<TargetedPracticeSummary|null>(null);const [error,setError]=useState('');useEffect(()=>{interviewService.getTargetedSummary(id).then(setData).catch(e=>setError(getApiErrorMessage(e)))},[id]);if(error)return <Alert message={error}/>;if(!data)return <LoadingSpinner label="Loading targeted practice summary..."/>;const change=data.scoreChange;const changeText=change==null?'Not enough previous evaluated answers to calculate a baseline.':change>=0?`Improved by ${change.toFixed(1)} points`:`Decreased by ${Math.abs(change).toFixed(1)} points`;return <main className="mx-auto max-w-3xl space-y-6"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">Targeted Practice Complete</p><h1 className="mt-2 text-3xl font-bold">{data.focusArea}</h1><p className="mt-2 text-slate-500">{data.skill||'Focused practice'} · {data.evaluatedCount}/{data.questionCount} evaluated</p></div><Card className="p-6"><h2 className="text-xl font-bold">Your Progress</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Previous" value={score(data.baselineScore)}/><Stat label="Targeted Practice" value={score(data.averageScore)}/><Stat label="Practice Score Change" value={change==null?'No baseline':`${change>=0?'+':''}${change.toFixed(1)}`}/></div><p className="mt-4 text-sm font-semibold">{changeText}</p>{change!=null&&change<0&&<p className="mt-2 text-sm text-slate-500">This practice score was lower than your previous evaluated performance. Review the feedback and try another focused session.</p>}<Rubrics current={data.rubricAverages} baseline={data.baselineRubricAverages}/></Card><div className="flex flex-wrap gap-3">{data.sourceInterviewId&&<Link className="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white" to={`/interviews/${data.sourceInterviewId}/coaching`}>Return to Coaching</Link>}<Link className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold dark:border-slate-700" to="/practice/targeted" state={{sourceInterviewId:data.sourceInterviewId,focusArea:data.focusArea,skill:data.skill}}>Practice Again</Link><Link className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold dark:border-slate-700" to="/history">History</Link></div></main>}
function score(value:number|null){return value==null?'No data':`${value.toFixed(1)} / 100`}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800/60"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
function Rubrics({current,baseline}:{current:RubricAverages;baseline:RubricAverages|null}){return <div className="mt-6 space-y-2">{(['relevance','correctness','completeness','communication'] as const).map(key=>current[key]!=null?<p key={key} className="flex justify-between text-sm"><span className="capitalize">{key}</span><strong>{baseline?.[key]!=null?`${baseline[key]!.toFixed(1)} → `:''}{current[key]!.toFixed(1)}</strong></p>:null)}</div>}
