"""Curated deterministic skill catalog and common resume aliases."""

SKILL_CATALOG: dict[str, dict[str, tuple[str, ...]]] = {
    "languages": {
        "Java": ("java",),
        "Python": ("python",),
        "JavaScript": ("javascript", "java script", "js"),
        "TypeScript": ("typescript", "type script", "ts"),
        "C": ("c",),
        "C++": ("c++", "cpp"),
        "C#": ("c#", "c sharp"),
        "SQL": ("sql",),
        "HTML": ("html", "html5"),
        "CSS": ("css", "css3"),
    },
    "backend": {
        "Spring Boot": ("spring boot", "springboot"),
        "Spring Security": ("spring security",),
        "Spring Data JPA": ("spring data jpa", "spring data"),
        "Hibernate": ("hibernate",),
        "Node.js": ("node.js", "node js", "nodejs", "node"),
        "Express.js": ("express.js", "express js", "expressjs"),
        "FastAPI": ("fastapi", "fast api"),
        "Django": ("django",),
        "Flask": ("flask",),
        "REST API": ("rest api", "restful api", "restful apis", "rest APIs"),
        "Microservices": ("microservices", "microservice"),
    },
    "frontend": {
        "React": ("react", "react.js", "react js", "reactjs"),
        "Angular": ("angular", "angular.js", "angularjs"),
        "Vue.js": ("vue.js", "vue js", "vuejs", "vue"),
        "Tailwind CSS": ("tailwind css", "tailwindcss", "tailwind"),
        "Bootstrap": ("bootstrap",),
        "Redux": ("redux",),
        "React Query": ("react query",),
    },
    "databases": {
        "PostgreSQL": ("postgresql", "postgres", "postgre sql"),
        "MySQL": ("mysql", "my sql"),
        "MongoDB": ("mongodb", "mongo db", "mongo"),
        "Redis": ("redis",),
        "SQLite": ("sqlite", "sqlite3"),
        "Oracle": ("oracle", "oracle db"),
    },
    "cloud_devops": {
        "Docker": ("docker",),
        "Kubernetes": ("kubernetes", "k8s"),
        "AWS": ("aws", "amazon web services"),
        "Azure": ("azure", "microsoft azure"),
        "GCP": ("gcp", "google cloud platform", "google cloud"),
        "GitHub Actions": ("github actions",),
        "CI/CD": ("ci/cd", "ci cd", "continuous integration continuous delivery"),
        "Jenkins": ("jenkins",),
        "Linux": ("linux",),
        "Nginx": ("nginx",),
    },
    "testing": {
        "JUnit": ("junit",),
        "Mockito": ("mockito",),
        "Pytest": ("pytest",),
        "Selenium": ("selenium",),
        "Postman": ("postman",),
    },
    "ai_data": {
        "Machine Learning": ("machine learning",),
        "Deep Learning": ("deep learning",),
        "NLP": ("nlp", "natural language processing"),
        "Pandas": ("pandas",),
        "NumPy": ("numpy",),
        "scikit-learn": ("scikit-learn", "scikit learn", "sklearn"),
        "TensorFlow": ("tensorflow", "tensor flow"),
        "PyTorch": ("pytorch", "py torch"),
        "OpenAI": ("openai", "open ai"),
        "LLM": ("llm", "large language model", "large language models"),
    },
    "tools": {
        "Git": ("git",),
        "GitHub": ("github", "git hub"),
        "Maven": ("maven",),
        "Gradle": ("gradle",),
        "Swagger": ("swagger",),
        "OpenAPI": ("openapi", "open api"),
        "VS Code": ("vs code", "vscode", "visual studio code"),
        "IntelliJ IDEA": ("intellij idea", "intellij"),
    },
}
